replicaCount: 3

zookeeper:
  enabled: true
  replicaCount: 1

externalZookeeper:
  enabled: false

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext

metrics:
  kafka:
    enabled: true
  jmx:
    enabled: true

persistence:
  enabled: false
